### ISSUE TITLE
CI w githubie

### ISSUE THREAD

**Issue by bartlomiejolczakdmcs** [IITA-DMCS-2122/iita_elixir#7]
1. Ktoś tworzy nowego brancha 
2. Robi PR
3. Odpala się automatyzacja która odpala testy
4. Po merge do brancha 'main' deploy na heroku: https://hexdocs.pm/phoenix/heroku.html

**Comment by krystiankowalski95** [comment]
```
remote: -----> Installing Hex
remote: * creating /app/.mix/archives/hex-1.0.1
remote: -----> Installing rebar
remote: * creating /app/.mix/rebar
remote: * creating /app/.mix/rebar3
remote: -----> Fetching app dependencies with mix
remote: ** (Mix.Config.LoadError) could not load config config/config.exs
remote:     ** (CompileError) config/config.exs:8: module Config is not loaded and could not be found
remote:     (elixir) lib/code.ex:176: Code.eval_string/3
remote:     (mix) lib/mix/config.ex:180: Mix.Config.read!/2
remote:  !     Push rejected, failed to compile Elixir app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to iita.
remote:
```

**Comment by FlaszKub** [comment]
https://github.com/mirego/accent/issues/112
